name: lugoyogo
description: "A yoga app"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  auto_route: ^10.2.0
  json_annotation: ^4.9.0
  dio: ^5.9.0
  firebase_core: ^4.2.1
  flutter_bloc: ^9.1.1
  get_it: ^9.0.5
  firebase_auth: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  auto_route_generator: ^10.2.5
  build_runner: ^2.10.1
  json_serializable: ^6.11.1

flutter:
  uses-material-design: true
